In [ ]:
import os
import requests
import pandas as pd
from dotenv import load_dotenv

load_dotenv()

API_KEY = os.getenv("API_KEY")
symbol = "INTC"

url = (
    f"https://www.alphavantage.co/query?"
    f"function=TIME_SERIES_DAILY&symbol={symbol}"
    f"&apikey={API_KEY}"
)

# THIS IS A NEW CHANGE

In [6]:
response = requests.get(url)

In [7]:
response.status_code

200

In [10]:
data = response.json()

In [11]:
print(data)

{'Meta Data': {'1. Information': 'Daily Prices (open, high, low, close) and Volumes', '2. Symbol': 'INTC', '3. Last Refreshed': '2026-05-19', '4. Output Size': 'Compact', '5. Time Zone': 'US/Eastern'}, 'Time Series (Daily)': {'2026-05-19': {'1. open': '106.9800', '2. high': '113.0699', '3. low': '102.4000', '4. close': '110.8000', '5. volume': '149041981'}, '2026-05-18': {'1. open': '113.4700', '2. high': '115.5400', '3. low': '103.8500', '4. close': '108.1700', '5. volume': '145763995'}, '2026-05-15': {'1. open': '109.7850', '2. high': '110.5700', '3. low': '105.0200', '4. close': '108.7700', '5. volume': '135205991'}, '2026-05-14': {'1. open': '114.6600', '2. high': '118.5700', '3. low': '113.1700', '4. close': '115.9300', '5. volume': '118279791'}, '2026-05-13': {'1. open': '124.1000', '2. high': '125.0000', '3. low': '116.4100', '4. close': '120.2900', '5. volume': '115364423'}, '2026-05-12': {'1. open': '124.3600', '2. high': '127.7900', '3. low': '115.0000', '4. close': '120.6100', '5. volume': '172516514'}, '2026-05-11': {'1. open': '130.8800', '2. high': '132.7500', '3. low': '123.9200', '4. close': '129.4400', '5. volume': '179486503'}, '2026-05-08': {'1. open': '111.8100', '2. high': '130.5700', '3. low': '111.8000', '4. close': '124.9200', '5. volume': '227681300'}, '2026-05-07': {'1. open': '111.0200', '2. high': '114.5100', '3. low': '109.1500', '4. close': '109.6200', '5. volume': '122699875'}, '2026-05-06': {'1. open': '110.9750', '2. high': '113.5000', '3. low': '106.5801', '4. close': '113.0100', '5. volume': '157320083'}, '2026-05-05': {'1. open': '100.5050', '2. high': '110.4800', '3. low': '100.0800', '4. close': '108.1500', '5. volume': '198481963'}, '2026-05-04': {'1. open': '99.1800', '2. high': '99.8200', '3. low': '95.6000', '4. close': '95.7800', '5. volume': '119294030'}, '2026-05-01': {'1. open': '93.2000', '2. high': '100.4500', '3. low': '92.6100', '4. close': '99.6200', '5. volume': '158502811'}, '2026-04-30': {'1. open': '95.6000', '2. high': '95.6900', '3. low': '91.5000', '4. close': '94.4800', '5. volume': '160597313'}, '2026-04-29': {'1. open': '86.1350', '2. high': '94.9500', '3. low': '85.8700', '4. close': '94.7500', '5. volume': '235070906'}, '2026-04-28': {'1. open': '81.2800', '2. high': '84.5900', '3. low': '80.8000', '4. close': '84.5200', '5. volume': '147773466'}, '2026-04-27': {'1. open': '83.6700', '2. high': '87.1000', '3. low': '82.6100', '4. close': '84.9900', '5. volume': '178820193'}, '2026-04-24': {'1. open': '82.2000', '2. high': '85.2200', '3. low': '79.6200', '4. close': '82.5400', '5. volume': '281405214'}, '2026-04-23': {'1. open': '66.1000', '2. high': '68.2800', '3. low': '65.4200', '4. close': '66.7800', '5. volume': '155141780'}, '2026-04-22': {'1. open': '67.9350', '2. high': '68.7700', '3. low': '64.9800', '4. close': '65.2700', '5. volume': '90267286'}, '2026-04-21': {'1. open': '67.1400', '2. high': '67.6700', '3. low': '65.6400', '4. close': '66.2600', '5. volume': '91402314'}, '2026-04-20': {'1. open': '68.4500', '2. high': '69.2050', '3. low': '64.4700', '4. close': '65.7000', '5. volume': '96851067'}, '2026-04-17': {'1. open': '68.8500', '2. high': '70.3250', '3. low': '67.7350', '4. close': '68.5000', '5. volume': '118831534'}, '2026-04-16': {'1. open': '64.9300', '2. high': '68.6100', '3. low': '64.2720', '4. close': '68.5000', '5. volume': '108328309'}, '2026-04-15': {'1. open': '63.7700', '2. high': '65.8400', '3. low': '62.8750', '4. close': '64.9400', '5. volume': '92051518'}, '2026-04-14': {'1. open': '65.1600', '2. high': '65.1800', '3. low': '62.0890', '4. close': '63.8100', '5. volume': '112796097'}, '2026-04-13': {'1. open': '62.1800', '2. high': '65.6500', '3. low': '62.1800', '4. close': '65.1800', '5. volume': '112110972'}, '2026-04-10': {'1. open': '61.5200', '2. high': '63.3900', '3. low': '60.7500', '4. close': '62.3800', '5. volume': '98624438'}, '2026-04-09': {'1. open': '58.4000', '2. high': '62.0799', '3. low': '58.3900', '4. close': '61.7200', '5. volume': '155609887'}, '2026-04-08': {'1. open': '55.3650', '2. high': '59.1700', '3. low': '54.8000', '4. close': '58.9500', '5. volume': '184599933'}, '2026-04-07': {'1. open': '51.9050', '2. high': '53.2700', '3. low': '51.2150', '4. close': '52.9100', '5. volume': '129543837'}, '2026-04-06': {'1. open': '50.8800', '2. high': '52.3850', '3. low': '49.8700', '4. close': '50.7800', '5. volume': '79978811'}, '2026-04-02': {'1. open': '46.0600', '2. high': '50.4900', '3. low': '46.0400', '4. close': '50.3800', '5. volume': '117134237'}, '2026-04-01': {'1. open': '45.0000', '2. high': '48.7700', '3. low': '44.9800', '4. close': '48.0300', '5. volume': '129598509'}, '2026-03-31': {'1. open': '41.9500', '2. high': '44.2300', '3. low': '41.6000', '4. close': '44.1300', '5. volume': '95294892'}, '2026-03-30': {'1. open': '43.7200', '2. high': '43.9900', '3. low': '40.6300', '4. close': '41.1900', '5. volume': '84596011'}, '2026-03-27': {'1. open': '43.6200', '2. high': '44.1300', '3. low': '42.8600', '4. close': '43.1300', '5. volume': '70002236'}, '2026-03-26': {'1. open': '46.2950', '2. high': '46.6000', '3. low': '43.9150', '4. close': '44.1000', '5. volume': '82841371'}, '2026-03-25': {'1. open': '45.8500', '2. high': '47.8450', '3. low': '45.4500', '4. close': '47.1800', '5. volume': '97467909'}, '2026-03-24': {'1. open': '43.5350', '2. high': '44.3100', '3. low': '43.2000', '4. close': '44.0600', '5. volume': '65323531'}, '2026-03-23': {'1. open': '44.5000', '2. high': '45.4600', '3. low': '43.7400', '4. close': '44.0100', '5. volume': '80772210'}, '2026-03-20': {'1. open': '46.9500', '2. high': '47.5500', '3. low': '43.6420', '4. close': '43.8700', '5. volume': '162814210'}, '2026-03-19': {'1. open': '43.9900', '2. high': '46.4400', '3. low': '43.6500', '4. close': '46.1800', '5. volume': '74051501'}, '2026-03-18': {'1. open': '44.2000', '2. high': '45.7050', '3. low': '44.0520', '4. close': '45.0300', '5. volume': '78056208'}, '2026-03-17': {'1. open': '46.0800', '2. high': '46.0800', '3. low': '43.9100', '4. close': '44.0600', '5. volume': '89061571'}, '2026-03-16': {'1. open': '47.9100', '2. high': '49.1700', '3. low': '45.6900', '4. close': '45.7600', '5. volume': '114199390'}, '2026-03-13': {'1. open': '45.9700', '2. high': '46.6500', '3. low': '45.3900', '4. close': '45.7700', '5. volume': '68386151'}, '2026-03-12': {'1. open': '47.4000', '2. high': '47.4350', '3. low': '45.1700', '4. close': '45.2500', '5. volume': '85110211'}, '2026-03-11': {'1. open': '46.8150', '2. high': '48.8300', '3. low': '46.6600', '4. close': '47.9800', '5. volume': '72480566'}, '2026-03-10': {'1. open': '45.4100', '2. high': '47.8750', '3. low': '45.4100', '4. close': '46.7800', '5. volume': '85233306'}, '2026-03-09': {'1. open': '42.7400', '2. high': '45.7600', '3. low': '41.6400', '4. close': '45.5800', '5. volume': '82937382'}, '2026-03-06': {'1. open': '44.6700', '2. high': '45.1800', '3. low': '43.2800', '4. close': '43.4200', '5. volume': '74698310'}, '2026-03-05': {'1. open': '44.8700', '2. high': '46.4800', '3. low': '44.7000', '4. close': '45.9500', '5. volume': '78229421'}, '2026-03-04': {'1. open': '44.0700', '2. high': '46.1250', '3. low': '43.2700', '4. close': '45.5800', '5. volume': '96628102'}, '2026-03-03': {'1. open': '43.4400', '2. high': '43.6850', '3. low': '42.1400', '4. close': '43.1000', '5. volume': '83971029'}, '2026-03-02': {'1. open': '44.2000', '2. high': '45.8100', '3. low': '43.9500', '4. close': '45.5000', '5. volume': '60705104'}, '2026-02-27': {'1. open': '44.4600', '2. high': '46.5600', '3. low': '44.4000', '4. close': '45.6100', '5. volume': '79327248'}, '2026-02-26': {'1. open': '46.7700', '2. high': '46.9500', '3. low': '44.3900', '4. close': '45.4600', '5. volume': '71457507'}, '2026-02-25': {'1. open': '46.0900', '2. high': '46.9700', '3. low': '45.0800', '4. close': '46.8800', '5. volume': '75645295'}, '2026-02-24': {'1. open': '44.0950', '2. high': '46.6000', '3. low': '43.5400', '4. close': '46.1200', '5. volume': '98872271'}, '2026-02-23': {'1. open': '44.0900', '2. high': '44.5500', '3. low': '43.1800', '4. close': '43.6300', '5. volume': '57130909'}, '2026-02-20': {'1. open': '43.8900', '2. high': '44.3900', '3. low': '42.8800', '4. close': '44.1100', '5. volume': '90743566'}, '2026-02-19': {'1. open': '44.9500', '2. high': '45.1700', '3. low': '43.9200', '4. close': '44.6200', '5. volume': '72724938'}, '2026-02-18': {'1. open': '45.9150', '2. high': '46.7700', '3. low': '44.8800', '4. close': '45.4600', '5. volume': '65306065'}, '2026-02-17': {'1. open': '45.9300', '2. high': '46.8299', '3. low': '45.4550', '4. close': '46.1800', '5. volume': '65802171'}, '2026-02-13': {'1. open': '45.7600', '2. high': '47.6900', '3. low': '44.9700', '4. close': '46.7900', '5. volume': '69740424'}, '2026-02-12': {'1. open': '47.8000', '2. high': '48.9500', '3. low': '46.1900', '4. close': '46.4800', '5. volume': '88321152'}, '2026-02-11': {'1. open': '48.1100', '2. high': '49.5500', '3. low': '46.8600', '4. close': '48.2900', '5. volume': '107681221'}, '2026-02-10': {'1. open': '50.4100', '2. high': '50.5393', '3. low': '46.7650', '4. close': '47.1300', '5. volume': '99832891'}, '2026-02-09': {'1. open': '49.5900', '2. high': '51.2200', '3. low': '47.5900', '4. close': '50.2400', '5. volume': '94841413'}, '2026-02-06': {'1. open': '49.1000', '2. high': '51.3000', '3. low': '48.8300', '4. close': '50.5900', '5. volume': '115600223'}, '2026-02-05': {'1. open': '47.5900', '2. high': '50.8600', '3. low': '46.7850', '4. close': '48.2400', '5. volume': '114307769'}, '2026-02-04': {'1. open': '49.5400', '2. high': '49.6980', '3. low': '47.0000', '4. close': '48.6000', '5. volume': '128702304'}, '2026-02-03': {'1. open': '50.0550', '2. high': '51.4900', '3. low': '48.4300', '4. close': '49.2500', '5. volume': '117661019'}, '2026-02-02': {'1. open': '45.6300', '2. high': '49.8400', '3. low': '45.5000', '4. close': '48.8100', '5. volume': '101414583'}, '2026-01-30': {'1. open': '48.9750', '2. high': '49.5777', '3. low': '45.9600', '4. close': '46.4700', '5. volume': '114920097'}, '2026-01-29': {'1. open': '47.5600', '2. high': '48.7700', '3. low': '46.9900', '4. close': '48.6600', '5. volume': '124256563'}, '2026-01-28': {'1. open': '46.6000', '2. high': '49.2850', '3. low': '46.3200', '4. close': '48.7800', '5. volume': '201995055'}, '2026-01-27': {'1. open': '43.9700', '2. high': '44.5300', '3. low': '43.0990', '4. close': '43.9300', '5. volume': '115345047'}, '2026-01-26': {'1. open': '44.2800', '2. high': '44.4600', '3. low': '42.2750', '4. close': '42.4900', '5. volume': '149407768'}, '2026-01-23': {'1. open': '46.8600', '2. high': '48.1300', '3. low': '44.4500', '4. close': '45.0700', '5. volume': '294675401'}, '2026-01-22': {'1. open': '54.2100', '2. high': '54.6000', '3. low': '53.0800', '4. close': '54.3200', '5. volume': '190066397'}, '2026-01-21': {'1. open': '50.3200', '2. high': '54.4100', '3. low': '50.1500', '4. close': '54.2500', '5. volume': '220565312'}, '2026-01-20': {'1. open': '47.3000', '2. high': '50.2300', '3. low': '47.0000', '4. close': '48.5600', '5. volume': '148554292'}, '2026-01-16': {'1. open': '49.2700', '2. high': '50.2100', '3. low': '46.7100', '4. close': '46.9600', '5. volume': '127314711'}, '2026-01-15': {'1. open': '49.3500', '2. high': '50.3900', '3. low': '47.8250', '4. close': '48.3200', '5. volume': '132328902'}, '2026-01-14': {'1. open': '48.9500', '2. high': '49.0000', '3. low': '47.4200', '4. close': '48.7200', '5. volume': '148225796'}, '2026-01-13': {'1. open': '45.8900', '2. high': '48.2400', '3. low': '45.2150', '4. close': '47.2900', '5. volume': '168656410'}, '2026-01-12': {'1. open': '44.2400', '2. high': '45.4500', '3. low': '43.8900', '4. close': '44.0600', '5. volume': '101989119'}, '2026-01-09': {'1. open': '41.8250', '2. high': '45.7265', '3. low': '41.5700', '4. close': '45.5500', '5. volume': '186691417'}, '2026-01-08': {'1. open': '42.6200', '2. high': '43.3400', '3. low': '40.6800', '4. close': '41.1100', '5. volume': '88241955'}, '2026-01-07': {'1. open': '40.1800', '2. high': '44.5700', '3. low': '40.1200', '4. close': '42.6300', '5. volume': '166028381'}, '2026-01-06': {'1. open': '39.8600', '2. high': '40.3100', '3. low': '38.9500', '4. close': '40.0400', '5. volume': '66395138'}, '2026-01-05': {'1. open': '41.5900', '2. high': '42.1000', '3. low': '39.2700', '4. close': '39.3700', '5. volume': '96665355'}, '2026-01-02': {'1. open': '37.7700', '2. high': '39.8600', '3. low': '37.7600', '4. close': '39.3800', '5. volume': '95396447'}, '2025-12-31': {'1. open': '37.3950', '2. high': '37.5800', '3. low': '36.8700', '4. close': '36.9000', '5. volume': '51524682'}, '2025-12-30': {'1. open': '36.9100', '2. high': '38.2600', '3. low': '36.8200', '4. close': '37.3000', '5. volume': '61935279'}, '2025-12-29': {'1. open': '36.0100', '2. high': '36.7950', '3. low': '35.8200', '4. close': '36.6800', '5. volume': '38062295'}, '2025-12-26': {'1. open': '36.1700', '2. high': '36.4900', '3. low': '35.8500', '4. close': '36.2000', '5. volume': '28779396'}, '2025-12-24': {'1. open': '35.1700', '2. high': '36.1750', '3. low': '34.9500', '4. close': '36.1600', '5. volume': '37443756'}}}

In [14]:
data.keys()

dict_keys(['Meta Data', 'Time Series (Daily)'])

In [16]:
daily_data = data["Time Series (Daily)"]

In [ ]:
daily_data.items()

{'2026-05-19': {'1. open': '106.9800',
  '2. high': '113.0699',
  '3. low': '102.4000',
  '4. close': '110.8000',
  '5. volume': '149041981'},
 '2026-05-18': {'1. open': '113.4700',
  '2. high': '115.5400',
  '3. low': '103.8500',
  '4. close': '108.1700',
  '5. volume': '145763995'},
 '2026-05-15': {'1. open': '109.7850',
  '2. high': '110.5700',
  '3. low': '105.0200',
  '4. close': '108.7700',
  '5. volume': '135205991'},
 '2026-05-14': {'1. open': '114.6600',
  '2. high': '118.5700',
  '3. low': '113.1700',
  '4. close': '115.9300',
  '5. volume': '118279791'},
 '2026-05-13': {'1. open': '124.1000',
  '2. high': '125.0000',
  '3. low': '116.4100',
  '4. close': '120.2900',
  '5. volume': '115364423'},
 '2026-05-12': {'1. open': '124.3600',
  '2. high': '127.7900',
  '3. low': '115.0000',
  '4. close': '120.6100',
  '5. volume': '172516514'},
 '2026-05-11': {'1. open': '130.8800',
  '2. high': '132.7500',
  '3. low': '123.9200',
  '4. close': '129.4400',
  '5. volume': '179486503'},
 '2026-05-08': {'1. open': '111.8100',
  '2. high': '130.5700',
  '3. low': '111.8000',
  '4. close': '124.9200',
  '5. volume': '227681300'},
 '2026-05-07': {'1. open': '111.0200',
  '2. high': '114.5100',
  '3. low': '109.1500',
  '4. close': '109.6200',
  '5. volume': '122699875'},
 '2026-05-06': {'1. open': '110.9750',
  '2. high': '113.5000',
  '3. low': '106.5801',
  '4. close': '113.0100',
  '5. volume': '157320083'},
 '2026-05-05': {'1. open': '100.5050',
  '2. high': '110.4800',
  '3. low': '100.0800',
  '4. close': '108.1500',
  '5. volume': '198481963'},
 '2026-05-04': {'1. open': '99.1800',
  '2. high': '99.8200',
  '3. low': '95.6000',
  '4. close': '95.7800',
  '5. volume': '119294030'},
 '2026-05-01': {'1. open': '93.2000',
  '2. high': '100.4500',
  '3. low': '92.6100',
  '4. close': '99.6200',
  '5. volume': '158502811'},
 '2026-04-30': {'1. open': '95.6000',
  '2. high': '95.6900',
  '3. low': '91.5000',
  '4. close': '94.4800',
  '5. volume': '160597313'},
 '2026-04-29': {'1. open': '86.1350',
  '2. high': '94.9500',
  '3. low': '85.8700',
  '4. close': '94.7500',
  '5. volume': '235070906'},
 '2026-04-28': {'1. open': '81.2800',
  '2. high': '84.5900',
  '3. low': '80.8000',
  '4. close': '84.5200',
  '5. volume': '147773466'},
 '2026-04-27': {'1. open': '83.6700',
  '2. high': '87.1000',
  '3. low': '82.6100',
  '4. close': '84.9900',
  '5. volume': '178820193'},
 '2026-04-24': {'1. open': '82.2000',
  '2. high': '85.2200',
  '3. low': '79.6200',
  '4. close': '82.5400',
  '5. volume': '281405214'},
 '2026-04-23': {'1. open': '66.1000',
  '2. high': '68.2800',
  '3. low': '65.4200',
  '4. close': '66.7800',
  '5. volume': '155141780'},
 '2026-04-22': {'1. open': '67.9350',
  '2. high': '68.7700',
  '3. low': '64.9800',
  '4. close': '65.2700',
  '5. volume': '90267286'},
 '2026-04-21': {'1. open': '67.1400',
  '2. high': '67.6700',
  '3. low': '65.6400',
  '4. close': '66.2600',
  '5. volume': '91402314'},
 '2026-04-20': {'1. open': '68.4500',
  '2. high': '69.2050',
  '3. low': '64.4700',
  '4. close': '65.7000',
  '5. volume': '96851067'},
 '2026-04-17': {'1. open': '68.8500',
  '2. high': '70.3250',
  '3. low': '67.7350',
  '4. close': '68.5000',
  '5. volume': '118831534'},
 '2026-04-16': {'1. open': '64.9300',
  '2. high': '68.6100',
  '3. low': '64.2720',
  '4. close': '68.5000',
  '5. volume': '108328309'},
 '2026-04-15': {'1. open': '63.7700',
  '2. high': '65.8400',
  '3. low': '62.8750',
  '4. close': '64.9400',
  '5. volume': '92051518'},
 '2026-04-14': {'1. open': '65.1600',
  '2. high': '65.1800',
  '3. low': '62.0890',
  '4. close': '63.8100',
  '5. volume': '112796097'},
 '2026-04-13': {'1. open': '62.1800',
  '2. high': '65.6500',
  '3. low': '62.1800',
  '4. close': '65.1800',
  '5. volume': '112110972'},
 '2026-04-10': {'1. open': '61.5200',
  '2. high': '63.3900',
  '3. low': '60.7500',
  '4. close': '62.3800',
  '5. volume': '98624438'},
 '2026-04-09': {'1. open': '58.4000',
  '2. high': '62.0799',
  '3. low': '58.3900',
  '4. close': '61.7200',
  '5. volume': '155609887'},
 '2026-04-08': {'1. open': '55.3650',
  '2. high': '59.1700',
  '3. low': '54.8000',
  '4. close': '58.9500',
  '5. volume': '184599933'},
 '2026-04-07': {'1. open': '51.9050',
  '2. high': '53.2700',
  '3. low': '51.2150',
  '4. close': '52.9100',
  '5. volume': '129543837'},
 '2026-04-06': {'1. open': '50.8800',
  '2. high': '52.3850',
  '3. low': '49.8700',
  '4. close': '50.7800',
  '5. volume': '79978811'},
 '2026-04-02': {'1. open': '46.0600',
  '2. high': '50.4900',
  '3. low': '46.0400',
  '4. close': '50.3800',
  '5. volume': '117134237'},
 '2026-04-01': {'1. open': '45.0000',
  '2. high': '48.7700',
  '3. low': '44.9800',
  '4. close': '48.0300',
  '5. volume': '129598509'},
 '2026-03-31': {'1. open': '41.9500',
  '2. high': '44.2300',
  '3. low': '41.6000',
  '4. close': '44.1300',
  '5. volume': '95294892'},
 '2026-03-30': {'1. open': '43.7200',
  '2. high': '43.9900',
  '3. low': '40.6300',
  '4. close': '41.1900',
  '5. volume': '84596011'},
 '2026-03-27': {'1. open': '43.6200',
  '2. high': '44.1300',
  '3. low': '42.8600',
  '4. close': '43.1300',
  '5. volume': '70002236'},
 '2026-03-26': {'1. open': '46.2950',
  '2. high': '46.6000',
  '3. low': '43.9150',
  '4. close': '44.1000',
  '5. volume': '82841371'},
 '2026-03-25': {'1. open': '45.8500',
  '2. high': '47.8450',
  '3. low': '45.4500',
  '4. close': '47.1800',
  '5. volume': '97467909'},
 '2026-03-24': {'1. open': '43.5350',
  '2. high': '44.3100',
  '3. low': '43.2000',
  '4. close': '44.0600',
  '5. volume': '65323531'},
 '2026-03-23': {'1. open': '44.5000',
  '2. high': '45.4600',
  '3. low': '43.7400',
  '4. close': '44.0100',
  '5. volume': '80772210'},
 '2026-03-20': {'1. open': '46.9500',
  '2. high': '47.5500',
  '3. low': '43.6420',
  '4. close': '43.8700',
  '5. volume': '162814210'},
 '2026-03-19': {'1. open': '43.9900',
  '2. high': '46.4400',
  '3. low': '43.6500',
  '4. close': '46.1800',
  '5. volume': '74051501'},
 '2026-03-18': {'1. open': '44.2000',
  '2. high': '45.7050',
  '3. low': '44.0520',
  '4. close': '45.0300',
  '5. volume': '78056208'},
 '2026-03-17': {'1. open': '46.0800',
  '2. high': '46.0800',
  '3. low': '43.9100',
  '4. close': '44.0600',
  '5. volume': '89061571'},
 '2026-03-16': {'1. open': '47.9100',
  '2. high': '49.1700',
  '3. low': '45.6900',
  '4. close': '45.7600',
  '5. volume': '114199390'},
 '2026-03-13': {'1. open': '45.9700',
  '2. high': '46.6500',
  '3. low': '45.3900',
  '4. close': '45.7700',
  '5. volume': '68386151'},
 '2026-03-12': {'1. open': '47.4000',
  '2. high': '47.4350',
  '3. low': '45.1700',
  '4. close': '45.2500',
  '5. volume': '85110211'},
 '2026-03-11': {'1. open': '46.8150',
  '2. high': '48.8300',
  '3. low': '46.6600',
  '4. close': '47.9800',
  '5. volume': '72480566'},
 '2026-03-10': {'1. open': '45.4100',
  '2. high': '47.8750',
  '3. low': '45.4100',
  '4. close': '46.7800',
  '5. volume': '85233306'},
 '2026-03-09': {'1. open': '42.7400',
  '2. high': '45.7600',
  '3. low': '41.6400',
  '4. close': '45.5800',
  '5. volume': '82937382'},
 '2026-03-06': {'1. open': '44.6700',
  '2. high': '45.1800',
  '3. low': '43.2800',
  '4. close': '43.4200',
  '5. volume': '74698310'},
 '2026-03-05': {'1. open': '44.8700',
  '2. high': '46.4800',
  '3. low': '44.7000',
  '4. close': '45.9500',
  '5. volume': '78229421'},
 '2026-03-04': {'1. open': '44.0700',
  '2. high': '46.1250',
  '3. low': '43.2700',
  '4. close': '45.5800',
  '5. volume': '96628102'},
 '2026-03-03': {'1. open': '43.4400',
  '2. high': '43.6850',
  '3. low': '42.1400',
  '4. close': '43.1000',
  '5. volume': '83971029'},
 '2026-03-02': {'1. open': '44.2000',
  '2. high': '45.8100',
  '3. low': '43.9500',
  '4. close': '45.5000',
  '5. volume': '60705104'},
 '2026-02-27': {'1. open': '44.4600',
  '2. high': '46.5600',
  '3. low': '44.4000',
  '4. close': '45.6100',
  '5. volume': '79327248'},
 '2026-02-26': {'1. open': '46.7700',
  '2. high': '46.9500',
  '3. low': '44.3900',
  '4. close': '45.4600',
  '5. volume': '71457507'},
 '2026-02-25': {'1. open': '46.0900',
  '2. high': '46.9700',
  '3. low': '45.0800',
  '4. close': '46.8800',
  '5. volume': '75645295'},
 '2026-02-24': {'1. open': '44.0950',
  '2. high': '46.6000',
  '3. low': '43.5400',
  '4. close': '46.1200',
  '5. volume': '98872271'},
 '2026-02-23': {'1. open': '44.0900',
  '2. high': '44.5500',
  '3. low': '43.1800',
  '4. close': '43.6300',
  '5. volume': '57130909'},
 '2026-02-20': {'1. open': '43.8900',
  '2. high': '44.3900',
  '3. low': '42.8800',
  '4. close': '44.1100',
  '5. volume': '90743566'},
 '2026-02-19': {'1. open': '44.9500',
  '2. high': '45.1700',
  '3. low': '43.9200',
  '4. close': '44.6200',
  '5. volume': '72724938'},
 '2026-02-18': {'1. open': '45.9150',
  '2. high': '46.7700',
  '3. low': '44.8800',
  '4. close': '45.4600',
  '5. volume': '65306065'},
 '2026-02-17': {'1. open': '45.9300',
  '2. high': '46.8299',
  '3. low': '45.4550',
  '4. close': '46.1800',
  '5. volume': '65802171'},
 '2026-02-13': {'1. open': '45.7600',
  '2. high': '47.6900',
  '3. low': '44.9700',
  '4. close': '46.7900',
  '5. volume': '69740424'},
 '2026-02-12': {'1. open': '47.8000',
  '2. high': '48.9500',
  '3. low': '46.1900',
  '4. close': '46.4800',
  '5. volume': '88321152'},
 '2026-02-11': {'1. open': '48.1100',
  '2. high': '49.5500',
  '3. low': '46.8600',
  '4. close': '48.2900',
  '5. volume': '107681221'},
 '2026-02-10': {'1. open': '50.4100',
  '2. high': '50.5393',
  '3. low': '46.7650',
  '4. close': '47.1300',
  '5. volume': '99832891'},
 '2026-02-09': {'1. open': '49.5900',
  '2. high': '51.2200',
  '3. low': '47.5900',
  '4. close': '50.2400',
  '5. volume': '94841413'},
 '2026-02-06': {'1. open': '49.1000',
  '2. high': '51.3000',
  '3. low': '48.8300',
  '4. close': '50.5900',
  '5. volume': '115600223'},
 '2026-02-05': {'1. open': '47.5900',
  '2. high': '50.8600',
  '3. low': '46.7850',
  '4. close': '48.2400',
  '5. volume': '114307769'},
 '2026-02-04': {'1. open': '49.5400',
  '2. high': '49.6980',
  '3. low': '47.0000',
  '4. close': '48.6000',
  '5. volume': '128702304'},
 '2026-02-03': {'1. open': '50.0550',
  '2. high': '51.4900',
  '3. low': '48.4300',
  '4. close': '49.2500',
  '5. volume': '117661019'},
 '2026-02-02': {'1. open': '45.6300',
  '2. high': '49.8400',
  '3. low': '45.5000',
  '4. close': '48.8100',
  '5. volume': '101414583'},
 '2026-01-30': {'1. open': '48.9750',
  '2. high': '49.5777',
  '3. low': '45.9600',
  '4. close': '46.4700',
  '5. volume': '114920097'},
 '2026-01-29': {'1. open': '47.5600',
  '2. high': '48.7700',
  '3. low': '46.9900',
  '4. close': '48.6600',
  '5. volume': '124256563'},
 '2026-01-28': {'1. open': '46.6000',
  '2. high': '49.2850',
  '3. low': '46.3200',
  '4. close': '48.7800',
  '5. volume': '201995055'},
 '2026-01-27': {'1. open': '43.9700',
  '2. high': '44.5300',
  '3. low': '43.0990',
  '4. close': '43.9300',
  '5. volume': '115345047'},
 '2026-01-26': {'1. open': '44.2800',
  '2. high': '44.4600',
  '3. low': '42.2750',
  '4. close': '42.4900',
  '5. volume': '149407768'},
 '2026-01-23': {'1. open': '46.8600',
  '2. high': '48.1300',
  '3. low': '44.4500',
  '4. close': '45.0700',
  '5. volume': '294675401'},
 '2026-01-22': {'1. open': '54.2100',
  '2. high': '54.6000',
  '3. low': '53.0800',
  '4. close': '54.3200',
  '5. volume': '190066397'},
 '2026-01-21': {'1. open': '50.3200',
  '2. high': '54.4100',
  '3. low': '50.1500',
  '4. close': '54.2500',
  '5. volume': '220565312'},
 '2026-01-20': {'1. open': '47.3000',
  '2. high': '50.2300',
  '3. low': '47.0000',
  '4. close': '48.5600',
  '5. volume': '148554292'},
 '2026-01-16': {'1. open': '49.2700',
  '2. high': '50.2100',
  '3. low': '46.7100',
  '4. close': '46.9600',
  '5. volume': '127314711'},
 '2026-01-15': {'1. open': '49.3500',
  '2. high': '50.3900',
  '3. low': '47.8250',
  '4. close': '48.3200',
  '5. volume': '132328902'},
 '2026-01-14': {'1. open': '48.9500',
  '2. high': '49.0000',
  '3. low': '47.4200',
  '4. close': '48.7200',
  '5. volume': '148225796'},
 '2026-01-13': {'1. open': '45.8900',
  '2. high': '48.2400',
  '3. low': '45.2150',
  '4. close': '47.2900',
  '5. volume': '168656410'},
 '2026-01-12': {'1. open': '44.2400',
  '2. high': '45.4500',
  '3. low': '43.8900',
  '4. close': '44.0600',
  '5. volume': '101989119'},
 '2026-01-09': {'1. open': '41.8250',
  '2. high': '45.7265',
  '3. low': '41.5700',
  '4. close': '45.5500',
  '5. volume': '186691417'},
 '2026-01-08': {'1. open': '42.6200',
  '2. high': '43.3400',
  '3. low': '40.6800',
  '4. close': '41.1100',
  '5. volume': '88241955'},
 '2026-01-07': {'1. open': '40.1800',
  '2. high': '44.5700',
  '3. low': '40.1200',
  '4. close': '42.6300',
  '5. volume': '166028381'},
 '2026-01-06': {'1. open': '39.8600',
  '2. high': '40.3100',
  '3. low': '38.9500',
  '4. close': '40.0400',
  '5. volume': '66395138'},
 '2026-01-05': {'1. open': '41.5900',
  '2. high': '42.1000',
  '3. low': '39.2700',
  '4. close': '39.3700',
  '5. volume': '96665355'},
 '2026-01-02': {'1. open': '37.7700',
  '2. high': '39.8600',
  '3. low': '37.7600',
  '4. close': '39.3800',
  '5. volume': '95396447'},
 '2025-12-31': {'1. open': '37.3950',
  '2. high': '37.5800',
  '3. low': '36.8700',
  '4. close': '36.9000',
  '5. volume': '51524682'},
 '2025-12-30': {'1. open': '36.9100',
  '2. high': '38.2600',
  '3. low': '36.8200',
  '4. close': '37.3000',
  '5. volume': '61935279'},
 '2025-12-29': {'1. open': '36.0100',
  '2. high': '36.7950',
  '3. low': '35.8200',
  '4. close': '36.6800',
  '5. volume': '38062295'},
 '2025-12-26': {'1. open': '36.1700',
  '2. high': '36.4900',
  '3. low': '35.8500',
  '4. close': '36.2000',
  '5. volume': '28779396'},
 '2025-12-24': {'1. open': '35.1700',
  '2. high': '36.1750',
  '3. low': '34.9500',
  '4. close': '36.1600',
  '5. volume': '37443756'}}

In [19]:
daily_data

rows = []

for date, values in daily_data.items():
    rows.append({
        "date": date,
        "open": float(values["1. open"]),
        "high": float(values["2. high"]),
        "low": float(values["3. low"]),
        "close": float(values["4. close"]),
        "volume": float(values["5. volume"]),
    })
    
rows

[{'date': '2026-05-19',
  'open': 106.98,
  'high': 113.0699,
  'low': 102.4,
  'close': 110.8,
  'volume': 149041981.0},
 {'date': '2026-05-18',
  'open': 113.47,
  'high': 115.54,
  'low': 103.85,
  'close': 108.17,
  'volume': 145763995.0},
 {'date': '2026-05-15',
  'open': 109.785,
  'high': 110.57,
  'low': 105.02,
  'close': 108.77,
  'volume': 135205991.0},
 {'date': '2026-05-14',
  'open': 114.66,
  'high': 118.57,
  'low': 113.17,
  'close': 115.93,
  'volume': 118279791.0},
 {'date': '2026-05-13',
  'open': 124.1,
  'high': 125.0,
  'low': 116.41,
  'close': 120.29,
  'volume': 115364423.0},
 {'date': '2026-05-12',
  'open': 124.36,
  'high': 127.79,
  'low': 115.0,
  'close': 120.61,
  'volume': 172516514.0},
 {'date': '2026-05-11',
  'open': 130.88,
  'high': 132.75,
  'low': 123.92,
  'close': 129.44,
  'volume': 179486503.0},
 {'date': '2026-05-08',
  'open': 111.81,
  'high': 130.57,
  'low': 111.8,
  'close': 124.92,
  'volume': 227681300.0},
 {'date': '2026-05-07',
  'open': 111.02,
  'high': 114.51,
  'low': 109.15,
  'close': 109.62,
  'volume': 122699875.0},
 {'date': '2026-05-06',
  'open': 110.975,
  'high': 113.5,
  'low': 106.5801,
  'close': 113.01,
  'volume': 157320083.0},
 {'date': '2026-05-05',
  'open': 100.505,
  'high': 110.48,
  'low': 100.08,
  'close': 108.15,
  'volume': 198481963.0},
 {'date': '2026-05-04',
  'open': 99.18,
  'high': 99.82,
  'low': 95.6,
  'close': 95.78,
  'volume': 119294030.0},
 {'date': '2026-05-01',
  'open': 93.2,
  'high': 100.45,
  'low': 92.61,
  'close': 99.62,
  'volume': 158502811.0},
 {'date': '2026-04-30',
  'open': 95.6,
  'high': 95.69,
  'low': 91.5,
  'close': 94.48,
  'volume': 160597313.0},
 {'date': '2026-04-29',
  'open': 86.135,
  'high': 94.95,
  'low': 85.87,
  'close': 94.75,
  'volume': 235070906.0},
 {'date': '2026-04-28',
  'open': 81.28,
  'high': 84.59,
  'low': 80.8,
  'close': 84.52,
  'volume': 147773466.0},
 {'date': '2026-04-27',
  'open': 83.67,
  'high': 87.1,
  'low': 82.61,
  'close': 84.99,
  'volume': 178820193.0},
 {'date': '2026-04-24',
  'open': 82.2,
  'high': 85.22,
  'low': 79.62,
  'close': 82.54,
  'volume': 281405214.0},
 {'date': '2026-04-23',
  'open': 66.1,
  'high': 68.28,
  'low': 65.42,
  'close': 66.78,
  'volume': 155141780.0},
 {'date': '2026-04-22',
  'open': 67.935,
  'high': 68.77,
  'low': 64.98,
  'close': 65.27,
  'volume': 90267286.0},
 {'date': '2026-04-21',
  'open': 67.14,
  'high': 67.67,
  'low': 65.64,
  'close': 66.26,
  'volume': 91402314.0},
 {'date': '2026-04-20',
  'open': 68.45,
  'high': 69.205,
  'low': 64.47,
  'close': 65.7,
  'volume': 96851067.0},
 {'date': '2026-04-17',
  'open': 68.85,
  'high': 70.325,
  'low': 67.735,
  'close': 68.5,
  'volume': 118831534.0},
 {'date': '2026-04-16',
  'open': 64.93,
  'high': 68.61,
  'low': 64.272,
  'close': 68.5,
  'volume': 108328309.0},
 {'date': '2026-04-15',
  'open': 63.77,
  'high': 65.84,
  'low': 62.875,
  'close': 64.94,
  'volume': 92051518.0},
 {'date': '2026-04-14',
  'open': 65.16,
  'high': 65.18,
  'low': 62.089,
  'close': 63.81,
  'volume': 112796097.0},
 {'date': '2026-04-13',
  'open': 62.18,
  'high': 65.65,
  'low': 62.18,
  'close': 65.18,
  'volume': 112110972.0},
 {'date': '2026-04-10',
  'open': 61.52,
  'high': 63.39,
  'low': 60.75,
  'close': 62.38,
  'volume': 98624438.0},
 {'date': '2026-04-09',
  'open': 58.4,
  'high': 62.0799,
  'low': 58.39,
  'close': 61.72,
  'volume': 155609887.0},
 {'date': '2026-04-08',
  'open': 55.365,
  'high': 59.17,
  'low': 54.8,
  'close': 58.95,
  'volume': 184599933.0},
 {'date': '2026-04-07',
  'open': 51.905,
  'high': 53.27,
  'low': 51.215,
  'close': 52.91,
  'volume': 129543837.0},
 {'date': '2026-04-06',
  'open': 50.88,
  'high': 52.385,
  'low': 49.87,
  'close': 50.78,
  'volume': 79978811.0},
 {'date': '2026-04-02',
  'open': 46.06,
  'high': 50.49,
  'low': 46.04,
  'close': 50.38,
  'volume': 117134237.0},
 {'date': '2026-04-01',
  'open': 45.0,
  'high': 48.77,
  'low': 44.98,
  'close': 48.03,
  'volume': 129598509.0},
 {'date': '2026-03-31',
  'open': 41.95,
  'high': 44.23,
  'low': 41.6,
  'close': 44.13,
  'volume': 95294892.0},
 {'date': '2026-03-30',
  'open': 43.72,
  'high': 43.99,
  'low': 40.63,
  'close': 41.19,
  'volume': 84596011.0},
 {'date': '2026-03-27',
  'open': 43.62,
  'high': 44.13,
  'low': 42.86,
  'close': 43.13,
  'volume': 70002236.0},
 {'date': '2026-03-26',
  'open': 46.295,
  'high': 46.6,
  'low': 43.915,
  'close': 44.1,
  'volume': 82841371.0},
 {'date': '2026-03-25',
  'open': 45.85,
  'high': 47.845,
  'low': 45.45,
  'close': 47.18,
  'volume': 97467909.0},
 {'date': '2026-03-24',
  'open': 43.535,
  'high': 44.31,
  'low': 43.2,
  'close': 44.06,
  'volume': 65323531.0},
 {'date': '2026-03-23',
  'open': 44.5,
  'high': 45.46,
  'low': 43.74,
  'close': 44.01,
  'volume': 80772210.0},
 {'date': '2026-03-20',
  'open': 46.95,
  'high': 47.55,
  'low': 43.642,
  'close': 43.87,
  'volume': 162814210.0},
 {'date': '2026-03-19',
  'open': 43.99,
  'high': 46.44,
  'low': 43.65,
  'close': 46.18,
  'volume': 74051501.0},
 {'date': '2026-03-18',
  'open': 44.2,
  'high': 45.705,
  'low': 44.052,
  'close': 45.03,
  'volume': 78056208.0},
 {'date': '2026-03-17',
  'open': 46.08,
  'high': 46.08,
  'low': 43.91,
  'close': 44.06,
  'volume': 89061571.0},
 {'date': '2026-03-16',
  'open': 47.91,
  'high': 49.17,
  'low': 45.69,
  'close': 45.76,
  'volume': 114199390.0},
 {'date': '2026-03-13',
  'open': 45.97,
  'high': 46.65,
  'low': 45.39,
  'close': 45.77,
  'volume': 68386151.0},
 {'date': '2026-03-12',
  'open': 47.4,
  'high': 47.435,
  'low': 45.17,
  'close': 45.25,
  'volume': 85110211.0},
 {'date': '2026-03-11',
  'open': 46.815,
  'high': 48.83,
  'low': 46.66,
  'close': 47.98,
  'volume': 72480566.0},
 {'date': '2026-03-10',
  'open': 45.41,
  'high': 47.875,
  'low': 45.41,
  'close': 46.78,
  'volume': 85233306.0},
 {'date': '2026-03-09',
  'open': 42.74,
  'high': 45.76,
  'low': 41.64,
  'close': 45.58,
  'volume': 82937382.0},
 {'date': '2026-03-06',
  'open': 44.67,
  'high': 45.18,
  'low': 43.28,
  'close': 43.42,
  'volume': 74698310.0},
 {'date': '2026-03-05',
  'open': 44.87,
  'high': 46.48,
  'low': 44.7,
  'close': 45.95,
  'volume': 78229421.0},
 {'date': '2026-03-04',
  'open': 44.07,
  'high': 46.125,
  'low': 43.27,
  'close': 45.58,
  'volume': 96628102.0},
 {'date': '2026-03-03',
  'open': 43.44,
  'high': 43.685,
  'low': 42.14,
  'close': 43.1,
  'volume': 83971029.0},
 {'date': '2026-03-02',
  'open': 44.2,
  'high': 45.81,
  'low': 43.95,
  'close': 45.5,
  'volume': 60705104.0},
 {'date': '2026-02-27',
  'open': 44.46,
  'high': 46.56,
  'low': 44.4,
  'close': 45.61,
  'volume': 79327248.0},
 {'date': '2026-02-26',
  'open': 46.77,
  'high': 46.95,
  'low': 44.39,
  'close': 45.46,
  'volume': 71457507.0},
 {'date': '2026-02-25',
  'open': 46.09,
  'high': 46.97,
  'low': 45.08,
  'close': 46.88,
  'volume': 75645295.0},
 {'date': '2026-02-24',
  'open': 44.095,
  'high': 46.6,
  'low': 43.54,
  'close': 46.12,
  'volume': 98872271.0},
 {'date': '2026-02-23',
  'open': 44.09,
  'high': 44.55,
  'low': 43.18,
  'close': 43.63,
  'volume': 57130909.0},
 {'date': '2026-02-20',
  'open': 43.89,
  'high': 44.39,
  'low': 42.88,
  'close': 44.11,
  'volume': 90743566.0},
 {'date': '2026-02-19',
  'open': 44.95,
  'high': 45.17,
  'low': 43.92,
  'close': 44.62,
  'volume': 72724938.0},
 {'date': '2026-02-18',
  'open': 45.915,
  'high': 46.77,
  'low': 44.88,
  'close': 45.46,
  'volume': 65306065.0},
 {'date': '2026-02-17',
  'open': 45.93,
  'high': 46.8299,
  'low': 45.455,
  'close': 46.18,
  'volume': 65802171.0},
 {'date': '2026-02-13',
  'open': 45.76,
  'high': 47.69,
  'low': 44.97,
  'close': 46.79,
  'volume': 69740424.0},
 {'date': '2026-02-12',
  'open': 47.8,
  'high': 48.95,
  'low': 46.19,
  'close': 46.48,
  'volume': 88321152.0},
 {'date': '2026-02-11',
  'open': 48.11,
  'high': 49.55,
  'low': 46.86,
  'close': 48.29,
  'volume': 107681221.0},
 {'date': '2026-02-10',
  'open': 50.41,
  'high': 50.5393,
  'low': 46.765,
  'close': 47.13,
  'volume': 99832891.0},
 {'date': '2026-02-09',
  'open': 49.59,
  'high': 51.22,
  'low': 47.59,
  'close': 50.24,
  'volume': 94841413.0},
 {'date': '2026-02-06',
  'open': 49.1,
  'high': 51.3,
  'low': 48.83,
  'close': 50.59,
  'volume': 115600223.0},
 {'date': '2026-02-05',
  'open': 47.59,
  'high': 50.86,
  'low': 46.785,
  'close': 48.24,
  'volume': 114307769.0},
 {'date': '2026-02-04',
  'open': 49.54,
  'high': 49.698,
  'low': 47.0,
  'close': 48.6,
  'volume': 128702304.0},
 {'date': '2026-02-03',
  'open': 50.055,
  'high': 51.49,
  'low': 48.43,
  'close': 49.25,
  'volume': 117661019.0},
 {'date': '2026-02-02',
  'open': 45.63,
  'high': 49.84,
  'low': 45.5,
  'close': 48.81,
  'volume': 101414583.0},
 {'date': '2026-01-30',
  'open': 48.975,
  'high': 49.5777,
  'low': 45.96,
  'close': 46.47,
  'volume': 114920097.0},
 {'date': '2026-01-29',
  'open': 47.56,
  'high': 48.77,
  'low': 46.99,
  'close': 48.66,
  'volume': 124256563.0},
 {'date': '2026-01-28',
  'open': 46.6,
  'high': 49.285,
  'low': 46.32,
  'close': 48.78,
  'volume': 201995055.0},
 {'date': '2026-01-27',
  'open': 43.97,
  'high': 44.53,
  'low': 43.099,
  'close': 43.93,
  'volume': 115345047.0},
 {'date': '2026-01-26',
  'open': 44.28,
  'high': 44.46,
  'low': 42.275,
  'close': 42.49,
  'volume': 149407768.0},
 {'date': '2026-01-23',
  'open': 46.86,
  'high': 48.13,
  'low': 44.45,
  'close': 45.07,
  'volume': 294675401.0},
 {'date': '2026-01-22',
  'open': 54.21,
  'high': 54.6,
  'low': 53.08,
  'close': 54.32,
  'volume': 190066397.0},
 {'date': '2026-01-21',
  'open': 50.32,
  'high': 54.41,
  'low': 50.15,
  'close': 54.25,
  'volume': 220565312.0},
 {'date': '2026-01-20',
  'open': 47.3,
  'high': 50.23,
  'low': 47.0,
  'close': 48.56,
  'volume': 148554292.0},
 {'date': '2026-01-16',
  'open': 49.27,
  'high': 50.21,
  'low': 46.71,
  'close': 46.96,
  'volume': 127314711.0},
 {'date': '2026-01-15',
  'open': 49.35,
  'high': 50.39,
  'low': 47.825,
  'close': 48.32,
  'volume': 132328902.0},
 {'date': '2026-01-14',
  'open': 48.95,
  'high': 49.0,
  'low': 47.42,
  'close': 48.72,
  'volume': 148225796.0},
 {'date': '2026-01-13',
  'open': 45.89,
  'high': 48.24,
  'low': 45.215,
  'close': 47.29,
  'volume': 168656410.0},
 {'date': '2026-01-12',
  'open': 44.24,
  'high': 45.45,
  'low': 43.89,
  'close': 44.06,
  'volume': 101989119.0},
 {'date': '2026-01-09',
  'open': 41.825,
  'high': 45.7265,
  'low': 41.57,
  'close': 45.55,
  'volume': 186691417.0},
 {'date': '2026-01-08',
  'open': 42.62,
  'high': 43.34,
  'low': 40.68,
  'close': 41.11,
  'volume': 88241955.0},
 {'date': '2026-01-07',
  'open': 40.18,
  'high': 44.57,
  'low': 40.12,
  'close': 42.63,
  'volume': 166028381.0},
 {'date': '2026-01-06',
  'open': 39.86,
  'high': 40.31,
  'low': 38.95,
  'close': 40.04,
  'volume': 66395138.0},
 {'date': '2026-01-05',
  'open': 41.59,
  'high': 42.1,
  'low': 39.27,
  'close': 39.37,
  'volume': 96665355.0},
 {'date': '2026-01-02',
  'open': 37.77,
  'high': 39.86,
  'low': 37.76,
  'close': 39.38,
  'volume': 95396447.0},
 {'date': '2025-12-31',
  'open': 37.395,
  'high': 37.58,
  'low': 36.87,
  'close': 36.9,
  'volume': 51524682.0},
 {'date': '2025-12-30',
  'open': 36.91,
  'high': 38.26,
  'low': 36.82,
  'close': 37.3,
  'volume': 61935279.0},
 {'date': '2025-12-29',
  'open': 36.01,
  'high': 36.795,
  'low': 35.82,
  'close': 36.68,
  'volume': 38062295.0},
 {'date': '2025-12-26',
  'open': 36.17,
  'high': 36.49,
  'low': 35.85,
  'close': 36.2,
  'volume': 28779396.0},
 {'date': '2025-12-24',
  'open': 35.17,
  'high': 36.175,
  'low': 34.95,
  'close': 36.16,
  'volume': 37443756.0}]

In [20]:
df = pd.DataFrame(rows)

df

          date     open      high     low   close       volume
0   2026-05-19  106.980  113.0699  102.40  110.80  149041981.0
1   2026-05-18  113.470  115.5400  103.85  108.17  145763995.0
2   2026-05-15  109.785  110.5700  105.02  108.77  135205991.0
3   2026-05-14  114.660  118.5700  113.17  115.93  118279791.0
4   2026-05-13  124.100  125.0000  116.41  120.29  115364423.0
..         ...      ...       ...     ...     ...          ...
95  2025-12-31   37.395   37.5800   36.87   36.90   51524682.0
96  2025-12-30   36.910   38.2600   36.82   37.30   61935279.0
97  2025-12-29   36.010   36.7950   35.82   36.68   38062295.0
98  2025-12-26   36.170   36.4900   35.85   36.20   28779396.0
99  2025-12-24   35.170   36.1750   34.95   36.16   37443756.0

[100 rows x 6 columns]

In [22]:
df.to_csv("../data/raw/intc_stock_data.csv", index=False)

In [23]:
df.head()

         date     open      high     low   close       volume
0  2026-05-19  106.980  113.0699  102.40  110.80  149041981.0
1  2026-05-18  113.470  115.5400  103.85  108.17  145763995.0
2  2026-05-15  109.785  110.5700  105.02  108.77  135205991.0
3  2026-05-14  114.660  118.5700  113.17  115.93  118279791.0
4  2026-05-13  124.100  125.0000  116.41  120.29  115364423.0